version: "3.8"

services:
  backend:
    build: .
    container_name: tech-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb+srv://techchallengegp7:5U9TNEijNKFCRn6Y@techchallenge.f8m1qcn.mongodb.net/?retryWrites=true&w=majority&appName=TechChallenge
      PORT: 3001
    networks:
      - tech-network

networks:
  tech-network:
    driver: bridge
